### ISSUE TITLE
Не активируется

### ISSUE THREAD

**Issue by aumkara** [Teplitsa/TeploBot#9]
Последний wp (4.6.1) и Теплобот (1.2).
При активации через панель плагинов говорит:

> Плагин не был активирован, потому что он вызвал фатальную ошибку.
> `Parse error: syntax error, unexpected '{' in /var/www/virtual/www/vu740/bot.veganbird.ru/data/wp-content/plugins/green-wp-telegram-bot-by-teplitsa/inc/core.php on line 234`

**Comment by scufa** [comment]
@aumkara, версия PHP? В документации плагина написано 5.3, но фактически нужно минимум 5.5

**Comment by aumkara** [comment]
@scufa, 5.3.3, ок

**Comment by Ahaenor** [comment]
Добрый день!

Спасибо, это хорошее замечание.
Действительно, сейчас в плагине используется try-finally, что начало поддерживаться только с PHP 5.5.

Мы обсудим, как решить или обойти эту проблему к ближайшему релизу.

- Сейчас самый простой способ - обновить PHP до 5.5.
- Другой вариант - в файле /inc/core.php (строка 234) закомментить инструкцию "finally {".
